# $NetBSD $

.include <bsd.own.mk>

TESTSDIR?=	${TESTSBASE}/lib/libc/multibyte

COPTS.t_c16rtomb.c += -Wno-unused-variable -Wno-unused-but-set-variable

TESTS_C+= t_c16rtomb


.include <bsd.test.mk>

